packages:
  # 系统模块 =====================================================
  - "api_admin"     #后端接口
  - "api_server"    #后端接口
  - "render_admin"  #前段页面
  - "vue_admin"     #前段页面

    # 工具包 =====================================================
  - "tool_web"
  - "tool_vue"
  
  
  - "api_end"       #前段页面
  - "web_admin"     #前段页面
  
  
  
  - "dayu01_web"     #前端
  - "dayu01_end"     #后端